version: "3.9"

services:

  traefik:
    image: traefik:v2.11
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    ports:
      - "9000:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - gateway
    restart: unless-stopped


  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend
    restart: unless-stopped


  postgres-user:
    image: postgres:16
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "54322:5432"
    volumes:
      - postgres_user:/var/lib/postgresql/data
    networks:
      - backend
    restart: unless-stopped


  user-service:
    build: ./services/user-service
    volumes:
      - ./services/user-service:/app
    depends_on:
      - postgres-user
      - rabbitmq
    networks:
      - gateway
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=gateway"
      - "traefik.http.routers.users.rule=Host(`localhost`) && PathPrefix(`/api/v2/auth`)"
      - "traefik.http.routers.users.entrypoints=web"
      - "traefik.http.services.users.loadbalancer.server.port=9000"
    restart: unless-stopped

  user-worker:
    build: ./services/user-service
    command: php artisan queue:work rabbitmq --sleep=3 --tries=3 --timeout=90
    depends_on:
      - postgres-user
      - rabbitmq
    networks:
      - backend
    restart: unless-stopped


  postgres-master:
    image: postgres:16
    environment:
      POSTGRES_DB: master_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "54323:5432"
    volumes:
      - postgres_master:/var/lib/postgresql/data
    networks:
      - backend
    restart: unless-stopped

  master-service:
    build: ./services/master-service
    volumes:
      - ./services/master-service:/app
    depends_on:
      - postgres-master
      - rabbitmq
    networks:
      - gateway
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=gateway"
      - "traefik.http.routers.master-data.rule=Host(`localhost`) && PathPrefix(`/api/v2/master-data`)"
      - "traefik.http.routers.master-data.entrypoints=web"
      - "traefik.http.services.master-data.loadbalancer.server.port=9000"
    restart: unless-stopped

  master-worker:
    build: ./services/master-service
    command: php artisan queue:work rabbitmq --sleep=3 --tries=3 --timeout=90
    depends_on:
      - postgres-master
      - rabbitmq
    networks:
      - backend
    restart: unless-stopped

  postgres-transaction:
    image: postgres:16
    environment:
      POSTGRES_DB: transaction_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "54324:5432"
    volumes:
      - postgres_transaction:/var/lib/postgresql/data
    networks:
      - backend
    restart: unless-stopped

  #  transaction-service:
  #    build: ./services/transaction-service
  #    environment:
  #      - PORT=3000
  #    container_name: go_fiber_api
  #    ports:
  #      - "3000:3000"
  #    labels:
  #      - "traefik.enable=true"
  #      - "traefik.docker.network=gateway"
  #      - "traefik.http.routers.transaction-data.rule=Host(`localhost`) && PathPrefix(`/api/v2/transaction-data`)"
  #      - "traefik.http.routers.transaction-data.entrypoints=web"
  #      - "traefik.http.services.transaction-data.loadbalancer.server.port=3000"
  #    depends_on:
  #      - postgres-transaction
  #    networks:
  #      - gateway
  #      - backend

  transaction-service-dev:
    build:
      context: ./services/transaction-service
      dockerfile: Dockerfile.dev
    image: transaction-service-dev:local
    container_name: transaction-service-dev
    working_dir: /src
    volumes:
      - ./services/transaction-service:/src:delegated
    environment:
      - PORT=3000
      - GOMAXPROCS=1
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=gateway"
      - "traefik.http.routers.transaction-data-dev.rule=Host(`localhost`) && PathPrefix(`/api/v2/transaction-data`)"
      - "traefik.http.routers.transaction-data-dev.entrypoints=web"
      - "traefik.http.services.transaction-data-dev.loadbalancer.server.port=3000"
      - "traefik.http.services.transaction-data-dev.loadbalancer.healthcheck.path=/api/v2/transaction-data/health"
      - "traefik.http.middlewares.transaction-data-dev-strip.stripprefix.prefixes=/api/v2/transaction-data"
    depends_on:
      - postgres-transaction

    networks:
      - gateway
      - backend

volumes:
  postgres_user:
  postgres_master:
  postgres_transaction:

networks:
  gateway:
    name: gateway
  backend:
    name: backend
