// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/laravel2004/auth-service/internal/handler/controller"
	"github.com/laravel2004/auth-service/internal/repository"
	"github.com/laravel2004/auth-service/internal/service"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func UserDI(db *gorm.DB) *controller.UserHandler {
	userRepository := repository.NewUserRepository(db)
	userService := service.NewUserService(userRepository)
	userHandler := controller.NewUserHandler(userService)
	return userHandler
}
